#!/usr/bin/env perl

use 5.010001;

use strict;
use warnings;

use App::Sam;
use File::Spec;
use Getopt::Long 2.33 qw{ :config auto_version pass_through };
use Pod::Usage;

our $VERSION = '0.000_001';

use constant IS_TTY	=> -t STDOUT;

use open qw{ :std :encoding(utf-8) };

my %opt;

GetOptions( \%opt,
    qw{ dump! },
    help => sub { pod2usage( { -verbose => 2 } ) },
) or pod2usage( { -verbose => 0 } );

my $dump = delete $opt{dump};
my $files_from = delete $opt{files_from};

my $sam = App::Sam->new(
    break	=> IS_TTY,
    color	=> IS_TTY,
    die		=> 1,
    argv	=> \@ARGV,
);

if ( $dump ) {

    require YAML;
    print YAML::Dump( $sam );

} else {

    push @ARGV, $sam->files_from();

    @ARGV
	or @ARGV = ( File::Spec->curdir() );

    $sam->process( $_ ) for @ARGV;
}

__END__

=head1 TITLE

sam - Search for strings in files, and possibly modify them

=head1 SYNOPSIS

 sam foo *.txt
 sam --help
 sam --version

=head1 OPTIONS

<<< replace boiler plate >>>

=head2 --help

This option displays the documentation for this script. The script then
exits.

=head2 --version

This option displays the version of this script. The script then exits.

=head1 DETAILS

<<< replace boiler plate >>>

=head1 AUTHOR

Thomas R. Wyant, III F<wyant at cpan dot org>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2023 by Thomas R. Wyant, III

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl 5.10.0. For more details, see the full text
of the licenses in the directory LICENSES.

This program is distributed in the hope that it will be useful, but
without any warranty; without even the implied warranty of
merchantability or fitness for a particular purpose.

=cut

# ex: set textwidth=72 :
